### ISSUE TITLE
Can I use this repo to download live stream m3u8 URL and save to local hard drive?

### ISSUE THREAD

**Issue by zydjohnHotmail** [n0tic/FFmpeg-UI-Utilizer#2]
Hello:
I happen to find your repo, and it seems to be interesting. However, as it is rather complicated, 
I can’t figure out yet how to download multiple M3U8 videos and save to local hard drive.
For example, I have the following 2 M3U8 videos in the URL:
http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8
http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
I want to launch 2 clients to download them at the same time, when finished, I want to save the files as local files: C:\1.mp4 and C:\2.mp4 and stop or dispose the client.
Please show me how I can do this with C#.
By the way, I am using Windows 10 Version 21H1, and Visual Studio 2019 Version 16.10.4.
Thanks,

**Comment by n0tic** [comment]
First of all, sorry for the late response. I have not been notified that this issue was created at all. 
Also, this repo does not contain a fully working application. Its under development and currently not being worked on as other things take priority at this moment.

> Can I use this repo to download live stream m3u8 URL and save to local hard drive?

To answer the question in the title first; Yes, you can save (record) live streams. Twitch for example.
However, some streams may require "Authentication" or "Active Sessions". Thats beyond my application although, if not mistaken, it may be implemented in FFmpeg so - it might be possible. I have no intention to add support for that.

> I happen to find your repo, and it seems to be interesting. However, as it is rather complicated, I can’t figure out yet how to download multiple M3U8 videos and save to local hard drive.

You manouver to the M3U8 tab, click "Add HLS/M3U8" - Add required information.
Once the list has been filled with streams/videos you simply press "Start M3U8" button and the download should start. The files will then be created in your desired output directory.


NOTE: Make sure that you select desired output folder and that you have FFmpeg downloaded. Updates tab should still work when updating. - Make sure you are not using the application build from "DEBUG". Those use another local testing path that would only work on my PC.

> I want to launch 2 clients to download them at the same time, when finished, I want to save the files as local files: C:\1.mp4 and C:\2.mp4 and stop or dispose the client.

Parallel download is not currently not implemented but all downloads are saved locally or to your networked path.
Once the all downloads in the process list is done the application will wait for further instructions.

> and stop or dispose the client

If you want the application itself to terminate once the download is complete that is not a feature I have implemented. However, if this is something you want you can always run FFmpeg itself by using either "cmd" or create a "shortcut"/.bat file.

> Please show me how I can do this with C#.

As previously mentionend, the code and application is quite hastely written and not even finished. I feel like I could make improvements pretty much everywhere. However, you are free to use it and experiment if you want to.

First of, this system is pretty simple in theory. It launches FFmpeg with the arguments/options passed by the user settings/information, wait for ffmpeg to close, repeat.

It uses the system M3U8Processor and it's constructor takes the "Main"-form as value (reference to "UI"). This is how the system communicates with the main UI later. To process the downloads it requires M3U8ProcesserData to be passed through by using the ProcessFileQueue method. 

So, techically, heres what you can do:
1. "M3U8Processor" needs to be created.
2. "M3U8ProcesserData" needs to be created (Constructor needs output folder path and boolean to either hide/show console)
3. Once "M3U8ProcesserData" is created it need values passed with the "Add" method. Provide string name and string url for each download.
3. Pass "M3U8ProcesserData" through "ProcessFileQueue"
4. Wait for download to finish.

NOTE: Some references, for example ffmpeg, use references from outside itself and needs to be set in application settings. (main.settings.ffmpegPath)

----------------------------------------------------------- END NOTES -----------------------------------------------------------
Video bellow shows me updating/installing/downloading FFmpeg using the application, downloading and viewing files you provided. It also shows me recording live twitch stream in the end. (Set speed in youtube player)
Video: https://www.youtube.com/watch?v=QaDThvJSxBA

NOTES:
I will go back to this project, clean up and build modules to make it a bit easier when I get more time.

Also, this issue-thread will be locked in a few days if no response comes up. Good luck, have fun!
